version: '3.8'

services:
  companion:
    build:
      context: ./companion
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

  # ui:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.ui
  #   ports:
  #     - "3000:80"
  #   networks:
  #     - app-network

  uploadpilot:
    build:
      context: ./uploadpilot
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
