services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  # mysqldb:
  #   extends:
  #     file: ./infra/supertokens/docker-compose.yaml
  #     service: mysqldb

  # supertokens:
  #   extends:
  #     file: ./infra/supertokens/docker-compose.yaml
  #     service: supertokens

volumes:
  # mongodb_data:
  mysql_data:

