services:
  # mongodb:
  #   image: mongo:latest
  #   container_name: mongodb
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb_data:/data/db
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=root
  #     - MONGO_INITDB_ROOT_PASSWORD=example

  companion:
    image: transloadit/companion:5.1.4
    container_name: companion
    ports:
      - "8090:8090"
    env_file:
      - .env
    volumes:
      - companion-data:/mnt/uppy-server-data


volumes:
  companion-data:
  # mongodb_data:

