AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
  
Resources:
  PostProcessingV1:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: PostProcessingV1
      CodeUri: ./code
      Runtime: python3.12
      Handler: app.lambda_handler
      Timeout: 300
      MemorySize: 128
      Role: !GetAtt PostProcessingV1Role.Arn
      Environment:
        Variables:
          ENVIRONMENT: "dev"

  PostProcessingV1Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: PostProcessingV1S3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                  - s3:DeleteObject
                Resource: "arn:aws:s3:::*"
        - PolicyName: PostProcessingV1CloudWatchLogs
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "arn:aws:logs:*:*:*"
