import {
  IconAutomation,
  IconBrandDocker,
  IconCode,
  IconDisc,
  IconFile,
  IconFileTypeCsv,
  IconFileTypeDoc,
  IconFileTypeDocx,
  IconFileTypeJpg,
  IconFileTypePdf,
  IconFileTypePng,
  IconFileTypePpt,
  IconFileTypeSvg,
  IconFileTypeXls,
  IconFileTypeZip,
  IconGif,
  IconHeadset,
  IconImageInPicture,
  IconVideo,
} from '@tabler/icons-react';
import { ReactNode } from 'react';

export const MIME_TYPE_ICONS: { [key: string]: any } = {
  'image/png': IconFileTypePng,
  'image/gif': IconGif,
  'image/jpeg': IconFileTypeJpg,
  'image/svg+xml': IconFileTypeSvg,
  'image/webp': IconImageInPicture,
  'image/avif': IconImageInPicture,
  'image/heic': IconImageInPicture,
  'image/heif': IconImageInPicture,
  'image/tiff': IconImageInPicture,
  'image/x-icon': IconImageInPicture,
  'image/bmp': IconImageInPicture,
  'image/jp2': IconImageInPicture,
  'image/vnd.ms-photo': IconImageInPicture,
  'image/x-raw': IconImageInPicture,
  'image/emf': IconImageInPicture,
  'image/wmf': IconImageInPicture,
  'image/hevc': IconImageInPicture,
  'image/pgf': IconImageInPicture,
  'image/x-exr': IconImageInPicture,
  'image/jls': IconImageInPicture,
  'image/vnd.openexr': IconImageInPicture,
  'image/fits': IconImageInPicture,
  'video/mp4': IconVideo,
  'video/webm': IconVideo,
  'video/quicktime': IconVideo,
  'video/x-matroska': IconVideo,
  'video/x-msvideo': IconVideo,
  'video/x-flv': IconVideo,
  'video/3gpp': IconVideo,
  'audio/x-mpegurl': IconVideo,
  'video/x-ms-asf': IconVideo,
  'video/mp2t': IconVideo,
  'application/x-shockwave-flash': IconVideo,
  'video/av1': IconVideo,
  'video/hevc': IconVideo,
  'video/h263': IconVideo,
  'video/h264': IconVideo,
  'video/x-prores': IconVideo,
  'video/dvd': IconVideo,
  'video/mxf': IconVideo,
  'video/ogg': IconVideo,
  'application/vnd.rn-realmedia': IconVideo,
  'video/cinepak': IconVideo,
  'video/divx': IconVideo,
  'video/theora': IconVideo,
  'audio/mpeg': IconHeadset,
  'audio/wav': IconHeadset,
  'audio/ogg': IconHeadset,
  'audio/flac': IconHeadset,
  'audio/aac': IconHeadset,
  'audio/aiff': IconHeadset,
  'audio/x-ms-wma': IconHeadset,
  'audio/midi': IconHeadset,
  'audio/alac': IconHeadset,
  'audio/opus': IconHeadset,
  'audio/speex': IconHeadset,
  'audio/amr': IconHeadset,
  'audio/mp4': IconHeadset,
  'audio/x-pn-realaudio': IconHeadset,
  'audio/x-xm': IconHeadset,
  'audio/x-s3m': IconHeadset,
  'audio/x-it': IconHeadset,
  'audio/x-mod': IconHeadset,
  'audio/x-cda': IconHeadset,
  'audio/x-scpls': IconHeadset,
  'audio/x-ms-asf': IconHeadset,
  'audio/vqf': IconHeadset,
  'audio/wavpack': IconHeadset,
  'application/zip': IconFileTypeZip,
  'application/x-rar': IconFileTypeZip,
  'application/x-7z-compressed': IconFileTypeZip,
  'application/x-tar': IconFileTypeZip,
  'application/gzip': IconFileTypeZip,
  'application/x-bzip2': IconFileTypeZip,
  'application/x-lzma': IconFileTypeZip,
  'application/x-xz': IconFileTypeZip,
  'application/vnd.ms-cab-compressed': IconFileTypeZip,
  'text/csv': IconFileTypeCsv,
  'application/pdf': IconFileTypePdf,
  'application/msword': IconFileTypeDocx,
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document':
    IconFileTypeDoc,
  'application/vnd.ms-excel': IconFileTypeXls,
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':
    IconFileTypeXls,
  'application/vnd.ms-powerpoint': IconFileTypePpt,
  'application/vnd.openxmlformats-officedocument.presentationml.presentation':
    IconFileTypePpt,
  'application/vnd.microsoft.portable-executable': IconAutomation,
  'application/x-msdos-program': IconAutomation,
  'application/x-ms-dos-executable': IconAutomation,
  'application/x-mach-binary': IconAutomation,
  'application/x-executable': IconAutomation,
  'application/javascript': IconCode,
  'text/x-python': IconCode,
  'text/x-java-source': IconCode,
  'text/x-csrc': IconCode,
  'text/x-c++src': IconCode,
  'application/typescript': IconCode,
  'application/json': IconCode,
  'application/x-yaml': IconCode,
  'text/html': IconCode,
  'text/css': IconCode,
  'text/markdown': IconCode,
  'application/sql': IconCode,
  'text/x-ruby': IconCode,
  'application/x-php': IconCode,
  'application/x-perl': IconCode,
  'application/x-shellscript': IconCode,
  'application/x-bash': IconCode,
  'text/x-makefile': IconCode,
  'application/x-swift': IconCode,
  'text/x-kotlin': IconCode,
  'text/x-objective-c': IconCode,
  'text/x-go': IconCode,
  'text/x-rust': IconCode,
  'application/x-powershell': IconCode,
  'text/x-lua': IconCode,
  'application/x-r': IconCode,
  'text/x-haskell': IconCode,
  'application/x-clojure': IconCode,
  'application/x-elixir': IconCode,
  'application/x-fsharp': IconCode,
  'application/x-scala': IconCode,
  'application/x-groovy': IconCode,
  'application/x-tcl': IconCode,
  'application/x-vbscript': IconCode,
  'application/x-actionscript': IconCode,
  'text/x-sass': IconCode,
  'text/x-less': IconCode,
  'application/x-coffeescript': IconCode,
  'text/x-vhdl': IconCode,
  'text/x-verilog': IconCode,
  'application/x-erlang': IconCode,
  'application/x-ocaml': IconCode,
  'application/dart': IconCode,
  'application/x-forth': IconCode,
  'application/x-scheme': IconCode,
  'application/x-lisp': IconCode,
  'application/x-xojo': IconCode,
  'text/x-hack': IconCode,
  'application/x-crystal': IconCode,
  'text/x-zig': IconCode,
  'application/x-vala': IconCode,
  'application/solidity': IconCode,
  'application/x-cobol': IconCode,
  'application/x-fortran': IconCode,
  'application/x-prolog': IconCode,
  'application/x-ladder-logic': IconCode,
  'application/xslt+xml': IconCode,
  'application/graphql': IconCode,
  'text/x-asm': IconCode,
  'application/plsql': IconCode,
  'application/vnd.docker.image.rootfs.diff.tar.gzip': IconBrandDocker,
  'application/vnd.docker.image.rootfs.diff.tar': IconBrandDocker,
  'application/x-virtualbox-ova': IconDisc,
  'application/x-vmdk': IconDisc,
  'application/x-lxc': IconDisc,
  'application/vnd.sylabs.sif': IconDisc,
  'application/x-iso9660-image': IconDisc,
  'application/x-raw-disk-image': IconDisc,
  'application/x-apple-diskimage': IconDisc,
  'application/x-qcow2': IconDisc,
  'application/x-vhd': IconDisc,
  'application/x-parallels-disk': IconDisc,
};

export const getFileIcon = (mimeType: string, size?: number): ReactNode => {
  const IconComponent = MIME_TYPE_ICONS[mimeType];
  return IconComponent ? (
    <IconComponent size={size} />
  ) : (
    <IconFile size={size} />
  );
};
