version = 0.1
[default.deploy.parameters]
stack_name = "ImageConverterPNGV1"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
resolve_s3 = false
s3_bucket = "sam-deployed-lambdas"
s3_prefix = "ImageConverterPNGV1"