services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/tmp/redis-data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 3
      timeout: 5s

  uploader:
    build:
      context: .
      dockerfile: Dockerfile.uploader
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOST=redis:6379
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      retries: 3
    networks:
      - app-network
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis-data:

networks:
  app-network:
